<Type Name="CustomAttributeFormatException" FullName="System.Reflection.CustomAttributeFormatException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="4527f253185e9bb12eb489edc2bd2ffabe7213d2" />
    <Meta Name="ms.sourcegitcommit" Value="6a0b904069161bbaec4ffd02aa7d9cf38c61e72e" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="es-ES" />
    <Meta Name="ms.lasthandoff" Value="06/24/2018" />
    <Meta Name="ms.locfileid" Value="36543248" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class CustomAttributeFormatException : FormatException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit CustomAttributeFormatException extends System.FormatException" />
  <TypeSignature Language="DocId" Value="T:System.Reflection.CustomAttributeFormatException" />
  <TypeSignature Language="VB.NET" Value="Public Class CustomAttributeFormatException&#xA;Inherits FormatException" />
  <TypeSignature Language="C++ CLI" Value="public ref class CustomAttributeFormatException : FormatException" />
  <TypeSignature Language="F#" Value="type CustomAttributeFormatException = class&#xA;    inherit FormatException" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.FormatException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="20440-101">Excepción que se produce cuando el formato binario del atributo personalizado no es válido.</span>
      <span class="sxs-lookup">
        <span data-stu-id="20440-101">The exception that is thrown when the binary format of a custom attribute is invalid.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="20440-102">`CustomAttributeFormatException` utiliza HRESULT COR_E_FORMAT, que tiene el valor 0 x 80131537.</span><span class="sxs-lookup"><span data-stu-id="20440-102">`CustomAttributeFormatException` uses the HRESULT COR_E_FORMAT which has the value 0x80131537.</span></span>  
  
 <span data-ttu-id="20440-103">`CustomAttributeFormatException` se produce si un atributo personalizado en un tipo de datos tiene un formato incorrecto, posiblemente debido a un error en la herramienta utilizada para crear el tipo de datos.</span><span class="sxs-lookup"><span data-stu-id="20440-103">`CustomAttributeFormatException` is thrown if a custom attribute on a data type is formatted incorrectly, possibly because of a bug in the tool used to create the data type.</span></span>  
  
 ]]></format>
    </remarks>
    <altmember cref="T:System.Exception" />
    <altmember cref="T:System.FormatException" />
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="20440-104">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.CustomAttributeFormatException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-104">Initializes a new instance of the <see cref="T:System.Reflection.CustomAttributeFormatException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public CustomAttributeFormatException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.CustomAttributeFormatException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; CustomAttributeFormatException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="20440-105">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.CustomAttributeFormatException" /> con las propiedades predeterminadas.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-105">Initializes a new instance of the <see cref="T:System.Reflection.CustomAttributeFormatException" /> class with the default properties.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="20440-106">Este constructor inicializa una instancia de `CustomAttributeFormatException` con una cadena de mensaje vacío y el problema raíz excepción establecido en `null`.</span><span class="sxs-lookup"><span data-stu-id="20440-106">This constructor initializes an instance of `CustomAttributeFormatException` with an empty message string and the root cause exception set to `null`.</span></span>  
  
 <span data-ttu-id="20440-107">Este constructor establece las propiedades de la `Exception` objeto como sigue:</span><span class="sxs-lookup"><span data-stu-id="20440-107">This constructor sets the properties of the `Exception` object as follows:</span></span>  
  
|<span data-ttu-id="20440-108">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="20440-108">Property</span></span>|<span data-ttu-id="20440-109">Valor</span><span class="sxs-lookup"><span data-stu-id="20440-109">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="20440-110">null</span><span class="sxs-lookup"><span data-stu-id="20440-110">null</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="20440-111">La cadena vacía ("").</span><span class="sxs-lookup"><span data-stu-id="20440-111">The empty string ("").</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public CustomAttributeFormatException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.CustomAttributeFormatException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; CustomAttributeFormatException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.Reflection.CustomAttributeFormatException : string -&gt; System.Reflection.CustomAttributeFormatException" Usage="new System.Reflection.CustomAttributeFormatException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="20440-112">Mensaje que indica la razón por la cual se produjo esta excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-112">The message that indicates the reason this exception was thrown.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="20440-113">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.CustomAttributeFormatException" /> con el mensaje especificado.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-113">Initializes a new instance of the <see cref="T:System.Reflection.CustomAttributeFormatException" /> class with the specified message.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="20440-114">Este constructor establece las propiedades del objeto de excepción como sigue:</span><span class="sxs-lookup"><span data-stu-id="20440-114">This constructor sets the properties of the Exception object as follows:</span></span>  
  
|<span data-ttu-id="20440-115">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="20440-115">Property</span></span>|<span data-ttu-id="20440-116">Valor</span><span class="sxs-lookup"><span data-stu-id="20440-116">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|`null`|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
        <altmember cref="T:System.FormatException" />
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected CustomAttributeFormatException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.CustomAttributeFormatException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; CustomAttributeFormatException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.Reflection.CustomAttributeFormatException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.Reflection.CustomAttributeFormatException" Usage="new System.Reflection.CustomAttributeFormatException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="20440-117">Datos para la serialización o deserialización del atributo personalizado.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-117">The data for serializing or deserializing the custom attribute.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="20440-118">Origen y destino para el atributo personalizado.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-118">The source and destination for the custom attribute.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="20440-119">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.CustomAttributeFormatException" /> con la serialización y la información de contexto especificadas.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-119">Initializes a new instance of the <see cref="T:System.Reflection.CustomAttributeFormatException" /> class with the specified serialization and context information.</span>
          </span>
        </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public CustomAttributeFormatException (string message, Exception inner);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception inner) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Reflection.CustomAttributeFormatException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, inner As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; CustomAttributeFormatException(System::String ^ message, Exception ^ inner);" />
      <MemberSignature Language="F#" Value="new System.Reflection.CustomAttributeFormatException : string * Exception -&gt; System.Reflection.CustomAttributeFormatException" Usage="new System.Reflection.CustomAttributeFormatException (message, inner)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="inner" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="20440-120">Mensaje de error que explica la razón de la excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-120">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="inner">
          <span data-ttu-id="20440-121">La excepción que es la causa de la excepción actual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-121">The exception that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="20440-122">Si el parámetro <c>inner</c> no es <see langword="null" />, la excepción actual se produce en un bloque <see langword="catch" /> que controla la excepción interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-122">If the <c>inner</c> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="20440-123">Inicializa una nueva instancia de la clase <see cref="T:System.Reflection.CustomAttributeFormatException" /> con el mensaje de error especificado y una referencia a la excepción interna que representa la causa de esta excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="20440-123">Initializes a new instance of the <see cref="T:System.Reflection.CustomAttributeFormatException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="20440-124">Una excepción que se produce como consecuencia directa de una excepción anterior debe incluir una referencia a esta última en la propiedad <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="20440-124">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="20440-125">La propiedad <xref:System.Exception.InnerException%2A> devuelve el mismo valor que se haya pasado al constructor, o bien `null` en caso de que la propiedad <xref:System.Exception.InnerException%2A> no le haya proporcionado al constructor el valor de la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="20440-125">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="20440-126">En la tabla siguiente se muestran los valores de propiedad iniciales para una instancia de <xref:System.Reflection.CustomAttributeFormatException>.</span><span class="sxs-lookup"><span data-stu-id="20440-126">The following table shows the initial property values for an instance of <xref:System.Reflection.CustomAttributeFormatException>.</span></span>  
  
|<span data-ttu-id="20440-127">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="20440-127">Property</span></span>|<span data-ttu-id="20440-128">Valor</span><span class="sxs-lookup"><span data-stu-id="20440-128">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="20440-129">El `inner` excepción.</span><span class="sxs-lookup"><span data-stu-id="20440-129">The `inner` exception.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="20440-130">Cadena con el mensaje de error.</span><span class="sxs-lookup"><span data-stu-id="20440-130">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Exception" />
      </Docs>
    </Member>
  </Members>
</Type>