<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="ServerException.xml" source-language="en-US" target-language="es-ES">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac50497df7776eb53e36625739cdf9b76066b4b912d.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">0497df7776eb53e36625739cdf9b76066b4b912d</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Runtime.Remoting.ServerException">
          <source>The exception that is thrown to communicate errors to the client when the client connects to non-.NET Framework applications that cannot throw exceptions.</source>
          <target state="translated">Excepción que se produce para comunicar errores al cliente cuando este se conecta a aplicaciones distintas de .NET Framework que no pueden producir excepciones.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.Remoting.ServerException">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> uses the HRESULT COR_E_SERVER, which has the value 0x8013150E.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> utiliza HRESULT COR_E_SERVER, que tiene el valor 0x8013150E.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.Remoting.ServerException">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> uses the default <ph id="ph2">&lt;xref:System.Object.Equals%2A&gt;</ph> implementation, which supports reference equality.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> usa el valor predeterminado <ph id="ph2">&lt;xref:System.Object.Equals%2A&gt;</ph> implementación, que admite la igualdad de referencia.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.Remoting.ServerException">
          <source>For a list of initial property values for an instance of <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph>, see the <ph id="ph2">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> constructors.</source>
          <target state="translated">Para obtener una lista de valores de propiedad iniciales para una instancia de <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph>, consulte el <ph id="ph2">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> constructores.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" uid="T:System.Runtime.Remoting.ServerException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph> class.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.ServerException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph> class with default properties.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph> con propiedades predeterminadas.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> inherits from the <ph id="ph2">&lt;xref:System.SystemException&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> hereda de la <ph id="ph2">&lt;xref:System.SystemException&gt;</ph> clase.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor">
          <source>The following table shows initial property values for an instance of the <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> class:</source>
          <target state="translated">La siguiente tabla muestra los valores de propiedad iniciales para una instancia de la <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> clase:</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor">
          <source>Property</source>
          <target state="translated">Propiedad.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor">
          <source>Value</source>
          <target state="translated">Valor</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor">
          <source>The empty string ("")</source>
          <target state="translated">La cadena vacía ("")</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String)">
          <source>The message that describes the exception</source>
          <target state="translated">Mensaje que describe la excepción</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph> class with a specified message.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph> con el mensaje especificado.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String)">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> inherits from the <ph id="ph2">&lt;xref:System.SystemException&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> hereda de la <ph id="ph2">&lt;xref:System.SystemException&gt;</ph> clase.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String)">
          <source>The following table shows initial property values for an instance of the <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> class:</source>
          <target state="translated">La siguiente tabla muestra los valores de propiedad iniciales para una instancia de la <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> clase:</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String)">
          <source>Property Type</source>
          <target state="translated">Tipo de propiedad</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String)">
          <source>Condition</source>
          <target state="translated">Condición</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String)">
          <source>The <ph id="ph1">`message`</ph> string</source>
          <target state="translated">El <ph id="ph1">`message`</ph> cadena</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">Mensaje de error que explica el motivo de la excepción.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">Excepción que es la causa de la excepción actual.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>InnerException<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated">Si el parámetro <bpt id="p1">&lt;c&gt;</bpt>InnerException<ept id="p1">&lt;/c&gt;</ept> no es <ph id="ph1">&lt;see langword="null" /&gt;</ph>, se genera la excepción actual en un bloque <ph id="ph2">&lt;see langword="catch" /&gt;</ph> que controla la excepción interna.</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.ServerException" /&gt;</ph> con el mensaje de error especificado y una referencia a la excepción interna que representa la causa de esta excepción.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">Una excepción que se produce como consecuencia directa de una excepción anterior debe incluir una referencia a esta última en la propiedad <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id="ph2">`null`</ph> if the <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.</source>
          <target state="translated">La propiedad <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> devuelve el mismo valor que se haya pasado al constructor, o bien <ph id="ph2">`null`</ph> en caso de que la propiedad <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> no le haya proporcionado al constructor el valor de la excepción interna.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>The following table shows initial property values for an instance of the <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> class:</source>
          <target state="translated">La siguiente tabla muestra los valores de propiedad iniciales para una instancia de la <ph id="ph1">&lt;xref:System.Runtime.Remoting.ServerException&gt;</ph> clase:</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>Property</source>
          <target state="translated">Propiedad.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>Value</source>
          <target state="translated">Valor</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>The inner exception reference</source>
          <target state="translated">La referencia a la excepción interna</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)">
          <source>The error message string</source>
          <target state="translated">La cadena de mensaje de error</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>